import { GoMail } from "react-icons/go";

export default {
  login: "Prakhar Nagore",
  id: 176013,
  node_id: "MDQ6VXNlcjE3NjAxMw==",
  avatar_url:
    "https://cdn.iconscout.com/icon/free/png-256/developer-2309906-1943816.png",
  gravatar_id: "",
  url: "https://api.github.com",
  html_url: "https://github.com",
  followers_url: "https://api.github.com/users/wesbos/followers",
  following_url: "https://api.github.com/users/wesbos/following{/other_user}",
  gists_url: "https://api.github.com/users/wesbos/gists{/gist_id}",
  starred_url: "https://api.github.com/users/wesbos/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/wesbos/subscriptions",
  organizations_url: "https://api.github.com/users/wesbos/orgs",
  repos_url: "https://api.github.com/users/wesbos/repos",
  events_url: "https://api.github.com/users/wesbos/events{/privacy}",
  received_events_url: "https://api.github.com/users/wesbos/received_events",
  type: "User",
  site_admin: false,
  name: "Prakhar Nagore",
  company: "Looking For Internship",
  blog: "prakharnagore000@gmail.com",
  location: "India",
  email: "prakharnagore000@GoMail.com",
  hireable: true,
  bio: "Currently Frontend Developer , roaring to Full-Stack🔥",
  twitter_username: null,
  public_repos: "10.1k+",
  public_gists: "1.8K+",
  followers: "1M+",
  following: 31,
  created_at: "2010-01-04T10:11:44Z",
  updated_at: "2021-08-28T20:04:33Z",
};
